services:
    dz.feature_flags.context.create:
        class: DZunke\FeatureFlagsBundle\EventListener\ContextCreator
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
