imports:
    - { resource: eventListener.yml }

services:
    dz.feature_flags.context:
        class: DZunke\FeatureFlagsBundle\Context

    dz.feature_flags.toggle:
        class: DZunke\FeatureFlagsBundle\Toggle

    dz.feature_flags.conditions_bag:
        class: DZunke\FeatureFlagsBundle\Toggle\ConditionBag

    dz.feature_flags.toggle.condition.ipaddress:
        class: DZunke\FeatureFlagsBundle\Toggle\Conditions\IpAddress
        calls:
            - [setContext, [@dz.feature_flags.context]]
        tags:
            -  { name: dz.feature_flags.toggle.condition, alias: ip_address }

    dz.feature_flags.toggle.condition.hostname:
        class: DZunke\FeatureFlagsBundle\Toggle\Conditions\Hostname
        calls:
            - [setContext, [@dz.feature_flags.context]]
        tags:
            -  { name: dz.feature_flags.toggle.condition, alias: hostname }

    dz.feature_flags.toggle.condition.percentage:
        class: DZunke\FeatureFlagsBundle\Toggle\Conditions\Percentage
        arguments: [@request_stack]
        calls:
            - [setContext, [@dz.feature_flags.context]]
        tags:
            -  { name: dz.feature_flags.toggle.condition, alias: percentage }

    dz.feature_flags.twig.feature_extension:
        class: DZunke\FeatureFlagsBundle\Twig\FeatureExtension
        arguments: [@dz.feature_flags.toggle]
        tags:
            - { name: twig.extension }
