language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.0
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*"

env:
  global:
    - deps=no

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - ./vendor/bin/phpunit -v
